service: serverless-node

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-s3-sync
  #- serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  s3Sync:
    - bucketName: srkicadeploymentbucket-2323
      localDir: UploadData

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

resources:
  Resources:
    SrkiBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: srkicadeploymentbucket-2323
