service: serverless-node

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

plugins:
  - serverless-s3-sync
  - serverless-offline
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: false
    packager: "yarn" # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

  s3Sync:
    - bucketName: srkicadeploymentbucket-2323
      localDir: UploadData

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
         path: graphql
         method: get
         cors: true

  playground:
    handler: graphql.graphqlHandler
    events:
      - http:
          path: playground
          method: get

resources:
  Resources:
    SrkiBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: srkicadeploymentbucket-2323
